### ISSUE TITLE
Why not use the package manager?

### ISSUE THREAD

**Issue by Noemata** [tristanlabelle/swift-winui-sample#1]
It appears you are the dev behind this:

https://github.com/thebrowsercompany/windows-samples

That sample uses the package manager.  Unfortunately, building from that repo yielded this:

Building for debugging...
lld-link: error: too many exported symbols (got 67393, max 65535)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[1/11] Linking D:\Swift_with_WinUI\windows-samples.build\x86_64-unknown-wind…

Is this why you opted for using CMAKE?

The package manager approach would be preferred.  So I'm wondering why you're not using that approach in your repos here.

**Comment by tristanlabelle** [comment]
Hi Noemata. I am not the dev behind windows-samples but a custodian of it. That project is unrelated to this one.

There are two fundamental limitations to the Swift package manager that make it unsuitable for larger or more complex projects:

- Inability to include external tools in the build, such as using `SwiftWinRT.exe` to generate code that is then built
- On Windows, a design flaw that results in every public symbol being exported on the binary, resulting in bloat and a hard limit on 65535 public symbols. This is what you ran into and what forced The Browser Company to move to CMake.

**Comment by Noemata** [comment]
Understood.  Thank you.
