### ISSUE TITLE
Failed to build: error: compiled module was created by an older version of the compiler; rebuild 'WindowsRuntime' and try again: 

### ISSUE THREAD

**Issue by Noemata** [tristanlabelle/swift-winui-sample#4]
I thought I rebuilt everything with the Swift compiler posted on thebrowsercompany repo today (just prior to the time of this message), but am getting the fault shown below.  Please advise.

[build] D:\Swift\swift-winui-sample\build\debug\Dependencies\WinRT\Sources\UWP\Projection\COMInterop+Extensions.swift:4:8: error: compiled module was created by an older version of the compiler; rebuild 'WindowsRuntime' and try again: D:\Swift\swift-winui-sample\build\debug\Dependencies\WinRT\Support\WindowsRuntime\WindowsRuntime.swiftmodule
[build]     2 | // swiftlint:disable all
[build]     3 | 
[build]     4 | import WindowsRuntime
[build]       |        `- error: compiled module was created by an older version of the compiler; rebuild 'WindowsRuntime' and try again: D:\Swift\swift-winui-sample\build\debug\Dependencies\WinRT\Support\WindowsRuntime\WindowsRuntime.swiftmodule

[build]     5 | import UWP_ABI

[build]     6 |

**Comment by Noemata** [comment]
I've corrected the issue of your nuget package pulling in older compiler bits.  Looks like I'm pretty close now.  Getting a missing directory message.  Holy, crazy number of references, batman!

**Comment by Noemata** [comment]
FYI: no coffee yet.

**Comment by tristanlabelle** [comment]
> error: compiled module was created by an older version of the compiler; rebuild 'WindowsRuntime' and try again

Builds artifacts are not compatible between toolchain versions. Delete the `build` folder and build fresh.

**Comment by Noemata** [comment]
Yup, figured that one out.  I also made a couple dumb mistakes when I rebuilt your nuget package.
