### ISSUE TITLE
Build link warnings and silent execution.

### ISSUE THREAD

**Issue by Noemata** [tristanlabelle/swift-winui-sample#7]
Although most of the bits appear to be working, including correct generation/deployment of the nuget package, I was not able to get a working build (something with a meaningful output).

Looks like your link flags are slightly incorrect.  Once again, it looks like I'm stepping ahead of where you were?

```
D:\Swift\swift-winui-sample>cmake --build --preset debug
[1/54] Linking Swift shared library Dependencies\WinRT\Build\UWP\Projection\UWP.dll
   Creating library Dependencies\\WinRT\\Build\\UWP\\Projection\\UWP.lib and object Dependencies\\WinRT\\Build\\UWP\\Projection\\UWP.exp
LINK : warning LNK4098: defaultlib 'msvcrtd.lib' conflicts with use of other libs; use /NODEFAULTLIB:library
[29/54] Linking Swift shared library Dependencies\WinRT\Build\WindowsAppSDK\Projection\WindowsAppSDK.dll
   Creating library Dependencies\\WinRT\\Build\\WindowsAppSDK\\Projection\\WindowsAppSDK.lib and object Dependencies\\WinRT\\Build\\WindowsAppSDK\\Projection\\WindowsAppSDK.exp
LINK : warning LNK4098: defaultlib 'msvcrtd.lib' conflicts with use of other libs; use /NODEFAULTLIB:library
[38/54] Linking Swift shared library Dependencies\WinRT\Build\WinUI\Projection\WinUI.dll
   Creating library Dependencies\\WinRT\\Build\\WinUI\\Projection\\WinUI.lib and object Dependencies\\WinRT\\Build\\WinUI\\Projection\\WinUI.exp
LINK : warning LNK4098: defaultlib 'msvcrtd.lib' conflicts with use of other libs; use /NODEFAULTLIB:library
[54/54] Linking Swift executable Sources\Sample.exe
   Creating library Sources\Sample.lib and object Sources\Sample.exp
LINK : warning LNK4098: defaultlib 'msvcrtd.lib' conflicts with use of other libs; use /NODEFAULTLIB:library
```

On my end, the Sample executes silently.  Am I missing DLLs to have this running?

Output Build Folder:
```
2024-11-25  07:45 PM             1,254 cmake_install.cmake
2024-11-25  07:55 PM           386,080 Microsoft.WindowsAppRuntime.Bootstrap.dll
2024-11-25  07:55 PM            26,533 Sample.emit-module.d
2024-11-25  07:55 PM         1,924,096 Sample.exe
2024-11-25  07:55 PM            11,333 Sample.exp
2024-11-25  07:55 PM            17,664 Sample.lib
2024-11-25  07:55 PM        41,745,408 UWP.dll
2024-11-25  07:55 PM        21,312,000 WindowsAppSDK.dll
2024-11-25  07:55 PM        62,811,136 WinUI.dll
```

**Comment by tristanlabelle** [comment]
Sorry, that's my bad. The `application` branch had some stuff I was trying out that broke things. You can revert `CMakePresets.json`, or use the same contents for that file as I now have for swift-winrt. The point of that change was to correctly generate debug information as I was having trouble hitting my breakpoints in this project. Filed #8 to address this.

I think my `application` branch is also crashing due to the experimental `IXamlMetadataProviderProtocol` support I was working on to get default xaml theming. If you remove the protocol implementation, `implements` and `_queryInterface` overrides, I think the app should run, but you might get white text on white background or something such.

**Comment by Noemata** [comment]
I'll let it slip just this once.  ;-)  I do like the direction this is headed in.  Was wondering if you could hide all those try expressions with an overload?  I'm not yet adept with Swift, so not in a position to do that kind of mucking around.  I'm hoping the Swift code will look mostly like it's C++ or C# equivalent.

**Comment by tristanlabelle** [comment]
> Was wondering if you could hide all those try expressions with an overload?

No. The WinRT and Swift error models butt into one another. WinRT allows any function to fail with any exception (aka HRESULT error code), so the projection into Swift means that every function must be `throws` and require `try`. The alternative would be to make the functions `fatalError()` if a bad HRESULT is returned, but this would prevent any form of error handling from WinRT APIs, which is definitely required in some cases. I'm allowing the consumers of the projection to choose whether they want to handle errors, or to put `try!` everywhere if they don't.

**Comment by tristanlabelle** [comment]
Try the latest main!

![image](https://github.com/user-attachments/assets/c0d01668-6a09-4ca1-9707-499f376e949d)
